### ISSUE TITLE
NoClassDefFoundError: org/apache/commons/lang/StringUtils

### ISSUE THREAD

**Issue by jjhenkel** [bblfsh/bash-driver#48]
Running the following command (where `./utils/install_server.sh` is from a fresh clone of [Redis](https://github.com/antirez/redis)): 

```
/target # bblfsh-cli -a localhost:9432 -l bash -m native --v2 ./utils/install_server.sh
```

Produces a UAST but also generates the following warning:

```
WARN: com.ansorgit.plugins.bash.lang.lexer._BashLexer
java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
  at com.ansorgit.plugins.bash.lang.util.HeredocSharedImpl.trimNewline(HeredocSharedImpl.java:56)
  at com.ansorgit.plugins.bash.lang.util.HeredocSharedImpl.cleanMarker(HeredocSharedImpl.java:29)
  at com.ansorgit.plugins.bash.lang.lexer.HeredocLexingState$HeredocMarkerInfo.<init>(HeredocLexingState.java:73)
  at com.ansorgit.plugins.bash.lang.lexer.HeredocLexingState.pushMarker(HeredocLexingState.java:54)
  at com.ansorgit.plugins.bash.lang.lexer._BashLexerBase.advance(_BashLexerBase.java:1642)
  at com.intellij.lexer.FlexAdapter.locateToken(FlexAdapter.java:110)
  at com.intellij.lexer.FlexAdapter.getTokenType(FlexAdapter.java:69)
  at com.intellij.lexer.MergingLexerAdapterBase.locateToken(MergingLexerAdapterBase.java:75)
  at com.intellij.lexer.MergingLexerAdapterBase.getTokenType(MergingLexerAdapterBase.java:48)
  at com.intellij.lang.impl.PsiBuilderImpl.a(PsiBuilderImpl.java:270)
  at com.intellij.lang.impl.PsiBuilderImpl.<init>(PsiBuilderImpl.java:191)
  at com.intellij.lang.impl.PsiBuilderImpl.<init>(PsiBuilderImpl.java:158)
  at com.intellij.lang.impl.PsiBuilderFactoryImpl.createBuilder(PsiBuilderFactoryImpl.java:78)
  at bblfsh.bash.Parser.builder(Parser.java:56)
  at bblfsh.bash.Parser.parse(Parser.java:30)
  at bblfsh.bash.Driver.processRequest(Driver.java:62)
  at bblfsh.bash.Driver.processOne(Driver.java:35)
  at bblfsh.bash.Driver.run(Driver.java:20)
  at bblfsh.bash.Main.main(Main.java:14)
```

Can this warning be fixed/silenced? Does the lack of this ClassDef adversely affect the generated UAST?

**Comment by creachadair** [comment]
I'm pretty sure this is a bug, since the driver is reporting an error trying to load one of its own classes. I don't know why this is a warning rather than an outright failure, but in any case it's wrong. :)

I would be a little surprised if the resulting UAST is complete.

**Comment by juanjux** [comment]
Looks like there is a dependency with Apache Commons Lang that the bash support lib is not declaring on its `build.gradle` file and thus is not being retrieved automatically. I'll add it manually in our `build.gradle`.

**Comment by juanjux** [comment]
Changed the dependency format, the change it's in v2.3.2, lots of thanks for your help.
